import turtle
turtle.fillcolor("Red")
turtle.begin_fill()
turtle.pendown()
turtle.right(45)
turtle.circle(70)
turtle.end_fill()
turtle.penup()
turtle.goto(-100, 28)
turtle.pendown()
turtle.fillcolor("Red")
turtle.begin_fill()
turtle.left(135)
turtle.circle(70)
turtle.end_fill()
turtle.penup()
turtle.goto(130, -140)
turtle.pendown()
turtle.fillcolor("Red")
turtle.begin_fill()
turtle.circle(170)
turtle.end_fill()
turtle.done()