import turtle 
turtle.fillcolor("Blue")
turtle.begin_fill()
turtle.right(0)
turtle.forward(100)
turtle.left(72)
turtle.forward(100)
turtle.left(72)
turtle.forward(100)
turtle.left(72)
turtle.forward(100)
turtle.left(72)
turtle.forward(100)
turtle.end_fill()
turtle.done()